name: ml_colon
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipython==7.10.0
  - jupyter
  - numpy
  - pandas
  - pip
  - scikit-learn
  - pre-commit
  - seaborn
  - matplotlib
  - mlflow
